services:
  - type: web
    name: telegram-relay-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python relay_bot.py
    plan: free
    healthCheckPath: /
    envVars:
      - key: API_ID
        value: 
      - key: API_HASH
        value:
      - key: PHONE
        value:
      - key: FIRST_GROUP
        value: 
      - key: SECOND_GROUP
        value:
      - key: PYTHON_VERSION
        value: 3.11.0
